/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.luxant.examples;

import java.time.Duration;

import com.luxant.sqs.SqsRequestor;

public class SqsServiceRequest {

    public String sendRequest(String queueName, String message) {
        String response = null;
        try (var r = new SqsRequestor("example-requestor")) {
            response = r.request(queueName, message, Duration.ofSeconds(20));
            System.out.printf("Received response: %s\n", response);
        } catch (InterruptedException ie) {
            Thread.currentThread().interrupt();
        } catch (Exception e) {
            System.out.println("Exception: " + e.getMessage());
        }
        return response;
    }

    public static void usage() {
        System.out.println("Usage: java com.luxant.examples.SqsServiceRequest <queue name> <payload>");
    }

    public static void main(String[] args) {
        if (args.length != 2) {
            usage();
            System.exit(1);
        }
        new SqsServiceRequest().sendRequest(args[0], args[1]);
    }
}
