/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.luxant.examples;

import com.luxant.sqs.SqsProducer;

public class SqsSend {
    public void sendMessage(String queueName, String message) {
        SqsProducer p = new SqsProducer();
        p.sendMessage(queueName, message);
        System.out.printf("Sent message to queue %s: %s\n", queueName, message);
    }

    public static void usage() {
        System.out.println("Usage:  java com.luxant.examples.SqsSend <queue name> <payload> ");
    }

    public static void main(String[] args) {
        if (args.length != 2) {
            usage();
            System.exit(1);
        }
        new SqsSend().sendMessage(args[0], args[1]);
    }
}
