/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.luxant.examples;

import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

import com.luxant.sqs.MessageHandler;
import com.luxant.sqs.SqsResponder;

import software.amazon.awssdk.services.sqs.model.Message;

public class SqsServiceResponder {

    ExecutorService executor = Executors.newSingleThreadExecutor();

    class EchoService implements MessageHandler, Runnable {
        SqsResponder responder;

        public EchoService(String listenQueue) {
            responder = new SqsResponder(listenQueue, this);
        }

        @Override
        public void onMsg(Message m) {
            String respMsg = String.format("Echo: %s", m.body());
            System.out.printf("Received request, responding with: %s.\n", respMsg);
            responder.reply(m, respMsg);
        }

        @Override
        public void run() {
            responder.run();
        }
    }

    public Future<Void> startResponding(String queueName) {
        try {
            return executor.submit(new EchoService(queueName), null);
        } catch (Exception e) {
            System.out.println(e);
            throw e;
        }
    }

    public static void usage() {
        System.out.println("Usage:  java com.luxant.examples.SqsServiceResponder <queue name>");
    }

    // For tests...
    public void stop() {
        executor.shutdown();
        try {
            executor.awaitTermination(20, TimeUnit.SECONDS);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }

    public static void main(String[] args) {
        if (args.length != 1) {
            usage();
            System.exit(1);
        }

        try {
            var f  = new SqsServiceResponder().startResponding(args[0]);
            System.out.printf("Listening on requests on queue %s\n", args[0]);
            f.get();
        } catch (ExecutionException e) {
            e.printStackTrace();
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }
}
